- name: telemetry-framework-apb playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    apb_action: provision
    kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/config"
  module_defaults:
    oc_adm_policy_user:
      kubeconfig: "{{ kubeconfig }}"
    oc_clusterrole:
      kubeconfig: "{{ kubeconfig }}"
    oc_obj:
      kubeconfig: "{{ kubeconfig }}"
    oc_project:
      kubeconfig: "{{ kubeconfig }}"
    oc_route:
      kubeconfig: "{{ kubeconfig }}"
    oc_secret:
      kubeconfig: "{{ kubeconfig }}"
    oc_service:
      kubeconfig: "{{ kubeconfig }}"
    oc_serviceaccount:
      kubeconfig: "{{ kubeconfig }}"
    oc_user:
      kubeconfig: "{{ kubeconfig }}"

  tasks:
    - name: Login to openshift
      command: "oc login -u {{ oc_login_username }}  -p {{ oc_login_password }}"
      when: cluster == "openshift"
            and oc_login_username is defined
            and oc_login_password is defined

    - include_role:
        name: lib_openshift

    - include_role:
        name: ansibleplaybookbundle.asb-modules

    - include_role:
        name: sa_telemetry
      vars:
        sa_telemetry_install: true
        sa_telemetry_namespace: "{{ namespace }}"

