- name: Create QDR ConfigMap
  oc_obj:
    state: "{{ state }}"
    name: qdrouterd-config-{{ node_label.name }}
    namespace: "{{ sa_telemetry_qdr_namespace }}"
    kind: ConfigMap
    content:
      path: /tmp/cmout-{{ node_label.name }}
      data: "{{ lookup('template', 'qdrouterd.conf.j2') | from_yaml }}"

- name: Create qdrouterd.json ConfigMap
  oc_obj:
    state: "{{ state }}"
    name: qdrouterd-json-{{ node_label.name }}
    namespace: "{{ sa_telemetry_qdr_namespace }}"
    kind: ConfigMap
    content:
      path: /tmp/cmout-{{ node_label.name }}
      data: "{{ lookup('template', 'qdrouterd.json.j2') | from_yaml }}"
