- name: Create QDR ConfigMap
  oc_obj:
    state: "{{ state }}"
    name: qdrouterd-config-{{ node_label.name }}
    namespace: "{{ sa_telemetry_qdr_namespace }}"
    kind: ConfigMap
    content:
      path: /tmp/cmout
      data: "{{ lookup('template', 'qdrouterd.conf.j2') | from_yaml }}"
  loop: "{{ sa_telemetry_node_labels }}"
  loop_control:
    index_var: label_index
