---
- set_fact:
    node_external_ip: "{{ hostvars[node_label.host]['ansible_default_ipv4']['address'] }}"
  when: not sa_telemetry_via_apb and node_label.ip is undefined

- set_fact:
    node_external_ip: "{{ node_label.ip }}"
  when: node_label.ip is defined

- set_fact:
    play_list:
      - services
      - configmaps
      - deployments

- set_fact:
    play_list: "{{ play_list | reverse | list }}"
  when: state == " absent"

- include_tasks: "{{ play }}.yml"
  loop: "{{ play_list }}"
  loop_control:
    loop_var: play
