- name: Create QDR Deployment
  oc_obj:
    state: "{{ state }}"
    force: yes
    name: qdr-{{ node_label.name }}
    namespace: "{{ sa_telemetry_qdr_namespace }}"
    kind: dc
    content:
      path: /tmp/dout
      data: "{{ lookup('template', 'qdr-deployment.yaml.j2') | from_yaml }}"
  ignore_errors: true
