---
- name: Deploy QDR routers
  include_tasks: deploy.yml
  loop: "{{ sa_telemetry_node_labels }}"
  loop_control:
    loop_var: node_label

- include_tasks: routes.yml
  with_items: "{{ sa_telemetry_node_labels }}"
  loop_control:
    loop_var: node_label
