---
- block:
    - name: Deploy QDR routers
      include_tasks: deploy.yml
      loop: "{{ sa_telemetry_node_labels }}"
      loop_control:
        loop_var: node_label
        index_var: label_index

    - include_tasks: routes.yml
      loop: "{{ sa_telemetry_node_labels }}"
      loop_control:
        loop_var: node_label
  when: state == "present"

- block:
    - include_tasks: routes.yml
      loop: "{{ sa_telemetry_node_labels }}"
      loop_control:
        loop_var: node_label

    - name: Deploy QDR routers
      include_tasks: deploy.yml
      loop: "{{ sa_telemetry_node_labels }}"
      loop_control:
        loop_var: node_label
        index_var: label_index
  when: state == "absent"
