- name: Create messaging Service
  oc_service:
    state: "{{ state }}"
    name: messaging-internal-{{ node_label.name }}
    namespace: "{{ sa_telemetry_qdr_namespace }}"
    labels:
      app: qdr-{{ node_label.name }}
      node: "{{ node_label.name }}"
    ports:
    - name: amqp
      port: 5672
    - name: amqps
      port: 5671
    selector:
      type: router
      node: "{{ node_label.name }}"
  loop: "{{ sa_telemetry_node_labels }}"

- name: Create external message Service
  oc_service:
    state: "{{ state }}"
    name: "{{ node_label.name }}-qdr"
    namespace: "{{ sa_telemetry_qdr_namespace }}"
    labels:
      app: qdr
      node: "{{ node_label.name }}"
    ports:
    - name: inter-router
      port: 20001
    selector:
      type: router
      node: "{{ node_label.name }}"
    external_ips:
      - "{{ node_external_ip }}"
  loop: "{{ sa_telemetry_node_labels }}"
