---
language: generic

git:
  depth: 1

services:
- docker

env:
  global:
  - REGISTRY_USER="nfvperobot"
  - secure: "sGs6T850gLa3ogzKIsY3VAo2AUZ8akWZHVOW5M5J2N5D6lW/ecZRhv18w9Ny0Yk+Dhihef8cpqiSz2FYnzWZPob/+F+R3K4hOUcq3fIfcUcntRgsvC4ep9Hb3TAS0c34wE76ZRLuk3dUcSq4CTmA6G6ZaliCzxmSgtPHVyZDtE3pjXKZgEBFXpjk1dLKYvSmHJdW908REGKh9gfeBD8brSN+3LPNa6sp+u+kypv6z3MtGBUKRkyXtdM1sN8PLk5Fb9YAjr269RpAo2fX4OpN2t61B+8ql1n8Iak1UU75KxMP6xJsaBk7Pfwbbvux8e9BOXJCLBDy4/oMSQvgAU3vMpP/VcAtmeFGcn/N+VUlRoxVuLIGLWVGtg3S/eWNBhlOT+PZ91XIDtCX0wLD63INCSFNJP2nkmUnDx07T4qjL9146qqgLWQiz4c9LcEWVpUGxdZm76MtlJWilx/ySg6RF9piy8e4MsGCBim7HYXOAQMaZjN8k5D6OmFiOw/xF0SkiVcSLWR8QeuY51obopCoISe/286ALjicwB38afpHxfaG2CXAyqCQ2Vf+dD5xqOfa9/8oT6UI3m0rMjIPhMVVcB5QIcNEFEz7fsWcjrl7oJRg7vOe3DoG/wGqWP7gvc8jZbQVdeI55gEAWXhmsB3paNRY8ymiWCRYF5Wm4N1kfcU="

before_deploy:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    - docker build --tag nfvpe/telemetry-framework-apb:latest .
    - docker images

deploy:
  provider: script
  script: docker push nfvpe/telemetry-framework-apb:latest
  on:
    branch: master

# vim: set ft=yaml ts=2 sts=2 sw=2 expandtab:
