---
- name: Create a template from qcow
  hosts: engine
  #  connection: local
  gather_facts: false

  vars_files:
    - ../vars/{{ password_file }}

  vars:
    engine_url: https://engine.dev.nfvpe.site/ovirt-engine/api
    engine_user: admin@internal
    engine_cafile: /etc/pki/ovirt-engine/ca.pem

    qcow_url: file:///root/rhel-server-7.6-x86_64-kvm.qcow2
    template_cluster: Default
    template_name: rhel76_template
    storage_domain: hosted_storage
    template_memory: 16GiB
    template_cpu: 4
    template_disk_size: 20GiB
    template_disk_storage: hosted_storage

  roles:
    - oVirt.image-template
