---
- name: oVirt infra
  hosts: engine
  gather_facts: false

  vars_files:
    # Contains encrypted `engine_password` variable using ansible-vault
    - ../vars/{{ password_file }}

  roles:
    - oVirt.vm-infra

  tasks:
    - fail:
        msg: Bail out because we are deleting the virtual machines. Expected error.
      when: vm_state == "absent"

- block:
    - name: Run prerequisites for OpenShift
      import_playbook: openshift-ansible-playbooks/prerequisites.yml

    - name: Install OpenShift on the nodes
      import_playbook: openshift-ansible-playbooks/deploy_cluster.yml

    - name: SA telemetry post-install
      import_playbook: sa-telemetry-postinstall.yml
  tags:
    - openshift-install
