---
# openshift metrics
- name: Create kube-state-metrics serviceaccount
  oc_serviceaccount:
    state: "{{ state }}"
    name: kube-state-metrics
    namespace: kube-system
  changed_when: false

- name: Create service for monitoring scheduler
  oc_service:
    name: kube-scheduler-prometheus-discovery
    namespace: kube-system
    state: "{{ state }}"
    labels:
      k8s-app: kube-scheduler
    selector:
      openshift.io/component: api
    ports:
      - name: http-metrics
        port: 10251
        targetPort: 10251
        protocol: TCP

- name: Create service for monitoring controller manager
  oc_service:
    name: kube-controller-manager-prometheus-discovery
    namespace: kube-system
    state: "{{ state }}"
    labels:
      k8s-app: kube-controller-manager
    selector:
      openshift.io/component: controllers
    ports:
      - name: http-metrics
        port: 10252
        targetPort: 10252
        protocol: TCP

- name: Create KSM service
  oc_service:
    name: kube-state-metrics
    namespace: "{{ sa_telemetry_ksm_namespace }}"
    state: "{{ state }}"
    labels:
      k8s-app: kube-state-metrics
    annotations:
      prometheus.io/scape: 'true'
    selector:
      k8s-app: kube-state-metrics
    ports:
      - name: http-metrics
        port: 8080
        targetPort: http-metrics
        protocol: TCP
      - name: telemetry
        port: 8081
        targetPort: telemetry
        protocol: TCP

- name: Create KSM role
  oc_obj:
    namespace: kube-system
    state: "{{ state }}"
    kind: Role
    name: kube-state-metrics-resizer
    content:
      path: /tmp/ksmroleout
      data: "{{ lookup('template', 'ksm-sa-telemetry-role.yaml.j2') | from_yaml }}"
  ignore_errors: true

- name: Create KSM role binding
  oc_obj:
    namespace: kube-system
    state: "{{ state }}"
    kind: RoleBinding
    name: kube-state-metrics-resizer
    content:
      path: /tmp/ksmrolebindingout
      data: "{{ lookup('template', 'ksm-sa-telemetry-rolebinding.yaml.j2') | from_yaml }}"
  ignore_errors: true

- name: Create KSM cluster role
  oc_obj:
    state: "{{ state }}"
    kind: ClusterRole
    name: kube-state-metrics
    content:
      path: /tmp/ksmclusterroleout
      data: "{{ lookup('template', 'ksm-sa-telemetry-clusterrole.yaml.j2') | from_yaml }}"
  ignore_errors: true

- name: Create KSM cluster role binding
  oc_obj:
    namespace: kube-system
    state: "{{ state }}"
    kind: ClusterRoleBinding
    name: kube-state-metrics
    content:
      path: /tmp/ksmclusterrolebindingout
      data: "{{ lookup('template', 'ksm-sa-telemetry-clusterrolebinding.yaml.j2') | from_yaml }}"
  ignore_errors: true

- name: Deploy kube-state-metrics
  oc_obj:
    namespace: kube-system
    state: "{{ state }}"
    kind: Deployment
    name: kube-state-metrics
    content:
      path: /tmp/ksmout
      data: "{{ lookup('template', 'ksm-sa-telemetry-deployment.yaml.j2') | from_yaml }}"
  ignore_errors: true

- name: Create service monitor for KSM
  oc_obj:
    namespace: "{{ sa_telemetry_ksm_namespace }}"
    state: "{{ state }}"
    kind: ServiceMonitor
    name: kube-state-metrics
    content:
      path: /tmp/ksmsmout
      data: "{{ lookup('template', 'ksm-sa-telemetry-servicemonitor.yaml.j2') | from_yaml }}"
  ignore_errors: true
