---
- name: PrometheusRules for SA Telemetry
  oc_obj:
    state: present
    name: sa-telemetry-prometheusrules
    namespace: "{{ sa_telemetry_prometheusrules_namespace }}"
    kind: PrometheusRule
    content:
      path: /tmp/prout
      data: "{{ lookup('template', 'prometheusrules-sa-telemetry.yaml.j2') | from_yaml }}"
  ignore_errors: true
