apiVersion: interconnectedcloud.github.io/v1alpha1
kind: Qdrouterd
metadata:
  name: qdr-white
spec:
  count: 1
  image: quay.io/interconnectedcloud/qdrouterd:1.5.0
  deploymentMode: lbfrontend
  addresses:
    - prefix: closest
      distribution: closest
    - prefix: multicast
      distribution: multicast
    - prefix: unicast
      distribution: closest
    - prefix: exclusive
      distribution: closest
    - prefix: broadcast
      distribution: multicast
    - prefix: collectd/telemetry
      distribution: multicast
  interRouterListeners:
    - name: from-openstack
      host: "0.0.0.0"
      port: 20001
  listeners:
    - port: 5671
    - port: 5672
    - port: 8672
      http: true
