apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    sa-telemetry-app: white-smartgateway
  name: white-smartgateway
spec:
  endpoints:
  - interval: 1s
    metricRelabelings:
    - action: labeldrop
      regex: pod
      sourcelabels: []
    - action: labeldrop
      regex: namespace
      sourcelabels: []
    - action: labeldrop
      regex: instance
      sourcelabels: []
    - action: labeldrop
      regex: job
      sourcelabels: []
    port: metrics
  namespaceSelector:
    matchNames:
    - sa-telemetry
  selector:
    matchLabels:
      sa-telemetry-app: white-smartgateway
