---
- name: Create QDR Route
  oc_route:
    state: present
    name: "{{ item.name }}"
    namespace: "{{ sa_telemetry_qdr_namespace }}"
    service_name: "{{ item.name }}"
  with_items:
    - name: "{{ node_label.name }}-qdr"
