- name: Add configuration (secret) for alertmanager
  oc_secret:
    state: "{{ state }}"
    name: alertmanager-sa
    namespace: "{{ sa_telemetry_alertmanager_namespace }}"
    contents:
      - path: alertmanager.yaml
        data: "{{ sa_telemetry_alertmanager_config }}"
