apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  name: prometheus-sa-telemetry
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - nodes
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
