apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: prometheus
spec:
  host: prometheus-sa-telemetry.apps.dev7.nfvpe.site
  port:
    targetPort: web
  to:
    kind: Service
    name: prometheus-operated
    weight: 100
  wildcardPolicy: None
