---
- name: Deploy Prometheus via Operator
  oc_obj:
    force: yes
    name: "{{ node.name }}"
    namespace: "{{ sa_telemetry_prometheus_namespace }}"
    state: "{{ state }}"
    kind: Prometheus
    content:
      path: /tmp/pout
      data: "{{ lookup('template', 'prometheus-sa-telemetry-deployment.yaml.j2') | from_yaml }}"
  retries: 50
  delay: 5
  register: result
  until: not result.failed

- name: Create direct services for prometheus (used by consumers)
  oc_service:
    name: "{{ sa_telemetry_prometheus_service_name }}-{{ node.name }}"
    namespace: "{{ sa_telemetry_prometheus_namespace }}"
    state: "{{ state }}"
    labels:
      sa-app: prometheus-{{ node.name }}
    ports:
    - name: prometheus
      port: "{{ sa_telemetry_prometheus_service_port }}"
      targetPort: "{{ sa_telemetry_prometheus_service_targetport }}"
      protocol: TCP
    selector:
      sa-app: prometheus-{{ node.name }}

- name: Create prometheus route for {{ node.name }}
  oc_route:
    state: "{{ state }}"
    name: "{{ node.name }}-prometheus"
    namespace: "{{ sa_telemetry_prometheus_namespace }}"
    service_name: "prometheus-{{ node.name }}"

- name: ServiceMonitor for prometheus {{ node.name }}
  oc_obj:
    namespace: "{{ sa_telemetry_prometheus_namespace }}"
    name: "prometheus-{{ node.name }}"
    state: "{{ state }}"
    kind: ServiceMonitor
    content:
      path: /tmp/psmout
      data: "{{ lookup('template', 'prometheus-sa-telemetry-service-monitor.yaml.j2') | from_yaml }}"
  ignore_errors: true
